### PR TITLE
Add xmlns in <math>

### PR DESCRIPTION
**Pull request by chaihahaha**
xmlns="http://www.w3.org/1998/Math/MathML" is needed in Microsoft Word mathml.

### CODE REVIEW

**Comment by roniemartinez** [comment]
@chaihahaha 

Thank you. Kindly send the PR to the **develop** branch first.

**Comment by chaihahaha** [comment]
Sorry, I have made changes to .travis.yml by mistake and don't know how to undo it. Maybe you can merge it to develop branch. Thank you for your awesome work!

**Comment by chaihahaha** [comment]
Sorry, I have made changes to .travis.yml by mistake and don't know how to undo it. Maybe you can merge it to develop branch. Thank you for your awesome work!

**Comment by roniemartinez** [comment]
@chaihahaha 2.7.1 is now available in PyPI

**Comment by roniemartinez** [comment]
@all-contributors please add @chaihahaha  for code

**Pull request merged**
