### PR TITLE
Add option to read TeX input from STDIN

### PR DESCRIPTION
**Pull request by miakramer**
I added a command line option to read the input from STDIN rather than from a file or string, which makes this easier to use as part of some pipelines and to call as a subprocess.

### CODE REVIEW

**Comment by roniemartinez** [comment]
Thanks @miakramer  🚀 

Can you also please update the README?

**Comment by miakramer** [comment]
Oh of course, sure! It looks like the phrasing of the optional arguments in `latex2mathml -h` has gone from `optional arguments:` to `options:`, would you like me to keep it the way it was and add the new options, or update the readme to be consistent with the help output?

**Comment by roniemartinez** [comment]
Sure! Please do so.

**Comment by roniemartinez** [comment]
@miakramer one more thing that we forgot. You just need to reformat for the linter to pass. `make format` should be available in the Makefile

```console
poetry run isort --check-only .
Skipping virtualenv creation, as specified in config file.
ERROR: /home/runner/work/latex2mathml/latex2mathml/latex2mathml/converter.py Imports are incorrectly sorted and/or formatted.
Skipped 1 files
make: *** [Makefile:[22](https://github.com/roniemartinez/latex2mathml/runs/7384455639?check_suite_focus=true#step:8:23): lint] Error 1
```

**Comment by miakramer** [comment]
Ah, so that's why there was so much failing CI?

**Pull request merged**
